export const countries = [
  { code: "BD", label: "Bangladesh", iso: "+880" },
  { code: "AD", label: "Andorra", iso: "+376" },
  {
    code: "AE",
    label: "United Arab Emirates",
    iso: "+971",
  },
  { code: "AF", label: "Afghanistan", iso: "+93" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    iso: "+1-268",
  },
  { code: "AI", label: "Anguilla", iso: "+1-264" },
  { code: "AL", label: "Albania", iso: "+355" },
  { code: "AM", label: "Armenia", iso: "+374" },
  { code: "AO", label: "Angola", iso: "+244" },
  { code: "AQ", label: "Antarctica", iso: "+672" },
  { code: "AR", label: "Argentina", iso: "+54" },
  { code: "AS", label: "American Samoa", iso: "+1-684" },
  { code: "AT", label: "Austria", iso: "+43" },
  {
    code: "AU",
    label: "Australia",
    iso: "+61",
    suggested: true,
  },
  { code: "AW", label: "Aruba", iso: "+297" },
  { code: "AX", label: "Alland Islands", iso: "+358" },
  { code: "AZ", label: "Azerbaijan", iso: "+994" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    iso: "+387",
  },
  { code: "BB", label: "Barbados", iso: "+1-246" },

  { code: "BE", label: "Belgium", iso: "+32" },
  { code: "BF", label: "Burkina Faso", iso: "+226" },
  { code: "BG", label: "Bulgaria", iso: "+359" },
  { code: "BH", label: "Bahrain", iso: "+973" },
  { code: "BI", label: "Burundi", iso: "+257" },
  { code: "BJ", label: "Benin", iso: "+229" },
  { code: "BL", label: "Saint Barthelemy", iso: "+590" },
  { code: "BM", label: "Bermuda", iso: "+1-441" },
  { code: "BN", label: "Brunei Darussalam", iso: "+673" },
  { code: "BO", label: "Bolivia", iso: "+591" },
  { code: "BR", label: "Brazil", iso: "+55" },
  { code: "BS", label: "Bahamas", iso: "+1-242" },
  { code: "BT", label: "Bhutan", iso: "+975" },
  { code: "BV", label: "Bouvet Island", iso: "+47" },
  { code: "BW", label: "Botswana", iso: "+267" },
  { code: "BY", label: "Belarus", iso: "+375" },
  { code: "BZ", label: "Belize", iso: "+501" },
  {
    code: "CA",
    label: "Canada",
    iso: "+1",
    suggested: true,
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    iso: "+61",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    iso: "+243",
  },
  {
    code: "CF",
    label: "Central African Republic",
    iso: "+236",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    iso: "+242",
  },
  { code: "CH", label: "Switzerland", iso: "+41" },
  { code: "CI", label: "Cote d'Ivoire", iso: "+225" },
  { code: "CK", label: "Cook Islands", iso: "+682" },
  { code: "CL", label: "Chile", iso: "+56" },
  { code: "CM", label: "Cameroon", iso: "+237" },
  { code: "CN", label: "China", iso: "+86" },
  { code: "CO", label: "Colombia", iso: "+57" },
  { code: "CR", label: "Costa Rica", iso: "+506" },
  { code: "CU", label: "Cuba", iso: "+53" },
  { code: "CV", label: "Cape Verde", iso: "+238" },
  { code: "CW", label: "Curacao", iso: "+599" },
  { code: "CX", label: "Christmas Island", iso: "+61" },
  { code: "CY", label: "Cyprus", iso: "+357" },
  { code: "CZ", label: "Czech Republic", iso: "+420" },
  {
    code: "DE",
    label: "Germany",
    iso: "+49",
    suggested: true,
  },
  { code: "DJ", label: "Djibouti", iso: "+253" },
  { code: "DK", label: "Denmark", iso: "+45" },
  { code: "DM", label: "Dominica", iso: "+1-767" },
  {
    code: "DO",
    label: "Dominican Republic",
    iso: "+1-809",
  },
  { code: "DZ", label: "Algeria", iso: "+213" },
  { code: "EC", label: "Ecuador", iso: "+593" },
  { code: "EE", label: "Estonia", iso: "+372" },
  { code: "EG", label: "Egypt", iso: "+20" },
  { code: "EH", label: "Western Sahara", iso: "+212" },
  { code: "ER", label: "Eritrea", iso: "+291" },
  { code: "ES", label: "Spain", iso: "+34" },
  { code: "ET", label: "Ethiopia", iso: "+251" },
  { code: "FI", label: "Finland", iso: "+358" },
  { code: "FJ", label: "Fiji", iso: "+679" },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    iso: "+500",
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    iso: "+691",
  },
  { code: "FO", label: "Faroe Islands", iso: "+298" },
  {
    code: "FR",
    label: "France",
    iso: "+33",
    suggested: true,
  },
  { code: "GA", label: "Gabon", iso: "+241" },
  { code: "GB", label: "United Kingdom", iso: "+44" },
  { code: "GD", label: "Grenada", iso: "+1-473" },
  { code: "GE", label: "Georgia", iso: "+995" },
  { code: "GF", label: "French Guiana", iso: "+594" },
  { code: "GG", label: "Guernsey", iso: "+44" },
  { code: "GH", label: "Ghana", iso: "+233" },
  { code: "GI", label: "Gibraltar", iso: "+350" },
  { code: "GL", label: "Greenland", iso: "+299" },
  { code: "GM", label: "Gambia", iso: "+220" },
  { code: "GN", label: "Guinea", iso: "+224" },
  { code: "GP", label: "Guadeloupe", iso: "+590" },
  { code: "GQ", label: "Equatorial Guinea", iso: "+240" },
  { code: "GR", label: "Greece", iso: "+30" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    iso: "+500",
  },
  { code: "GT", label: "Guatemala", iso: "+502" },
  { code: "GU", label: "Guam", iso: "+1-671" },
  { code: "GW", label: "Guinea-Bissau", iso: "+245" },
  { code: "GY", label: "Guyana", iso: "+592" },
  { code: "HK", label: "Hong Kong", iso: "+852" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    iso: "+672",
  },
  { code: "HN", label: "Honduras", iso: "+504" },
  { code: "HR", label: "Croatia", iso: "+385" },
  { code: "HT", label: "Haiti", iso: "+509" },
  { code: "HU", label: "Hungary", iso: "+36" },
  { code: "ID", label: "Indonesia", iso: "+62" },
  { code: "IE", label: "Ireland", iso: "+353" },
  { code: "IL", label: "Israel", iso: "+972" },
  { code: "IM", label: "Isle of Man", iso: "+44" },
  { code: "IN", label: "India", iso: "+91" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    iso: "+246",
  },
  { code: "IQ", label: "Iraq", iso: "+964" },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    iso: "+98",
  },
  { code: "IS", label: "Iceland", iso: "+354" },
  { code: "IT", label: "Italy", iso: "+39" },
  { code: "JE", label: "Jersey", iso: "+44" },
  { code: "JM", label: "Jamaica", iso: "+1-876" },
  { code: "JO", label: "Jordan", iso: "+962" },
  {
    code: "JP",
    label: "Japan",
    iso: "+81",
    suggested: true,
  },
  { code: "KE", label: "Kenya", iso: "+254" },
  { code: "KG", label: "Kyrgyzstan", iso: "+996" },
  { code: "KH", label: "Cambodia", iso: "+855" },
  { code: "KI", label: "Kiribati", iso: "+686" },
  { code: "KM", label: "Comoros", iso: "+269" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    iso: "+1-869",
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    iso: "+850",
  },
  { code: "KR", label: "Korea, Republic of", iso: "+82" },
  { code: "KW", label: "Kuwait", iso: "+965" },
  { code: "KY", label: "Cayman Islands", iso: "+1-345" },
  { code: "KZ", label: "Kazakhstan", iso: "+7" },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    iso: "+856",
  },
  { code: "LB", label: "Lebanon", iso: "+961" },
  { code: "LC", label: "Saint Lucia", iso: "+1-758" },
  { code: "LI", label: "Liechtenstein", iso: "+423" },
  { code: "LK", label: "Sri Lanka", iso: "+94" },
  { code: "LR", label: "Liberia", iso: "+231" },
  { code: "LS", label: "Lesotho", iso: "+266" },
  { code: "LT", label: "Lithuania", iso: "+370" },
  { code: "LU", label: "Luxembourg", iso: "+352" },
  { code: "LV", label: "Latvia", iso: "+371" },
  { code: "LY", label: "Libya", iso: "+218" },
  { code: "MA", label: "Morocco", iso: "+212" },
  { code: "MC", label: "Monaco", iso: "+377" },
  {
    code: "MD",
    label: "Moldova, Republic of",
    iso: "+373",
  },
  { code: "ME", label: "Montenegro", iso: "+382" },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    iso: "+590",
  },
  { code: "MG", label: "Madagascar", iso: "+261" },
  { code: "MH", label: "Marshall Islands", iso: "+692" },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    iso: "+389",
  },
  { code: "ML", label: "Mali", iso: "+223" },
  { code: "MM", label: "Myanmar", iso: "+95" },
  { code: "MN", label: "Mongolia", iso: "+976" },
  { code: "MO", label: "Macao", iso: "+853" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    iso: "+1-670",
  },
  { code: "MQ", label: "Martinique", iso: "+596" },
  { code: "MR", label: "Mauritania", iso: "+222" },
  { code: "MS", label: "Montserrat", iso: "+1-664" },
  { code: "MT", label: "Malta", iso: "+356" },
  { code: "MU", label: "Mauritius", iso: "+230" },
  { code: "MV", label: "Maldives", iso: "+960" },
  { code: "MW", label: "Malawi", iso: "+265" },
  { code: "MX", label: "Mexico", iso: "+52" },
  { code: "MY", label: "Malaysia", iso: "+60" },
  { code: "MZ", label: "Mozambique", iso: "+258" },
  { code: "NA", label: "Namibia", iso: "+264" },
  { code: "NC", label: "New Caledonia", iso: "+687" },
  { code: "NE", label: "Niger", iso: "+227" },
  { code: "NF", label: "Norfolk Island", iso: "+672" },
  { code: "NG", label: "Nigeria", iso: "+234" },
  { code: "NI", label: "Nicaragua", iso: "+505" },
  { code: "NL", label: "Netherlands", iso: "+31" },
  { code: "NO", label: "Norway", iso: "+47" },
  { code: "NP", label: "Nepal", iso: "+977" },
  { code: "NR", label: "Nauru", iso: "+674" },
  { code: "NU", label: "Niue", iso: "+683" },
  { code: "NZ", label: "New Zealand", iso: "+64" },
  { code: "OM", label: "Oman", iso: "+968" },
  { code: "PA", label: "Panama", iso: "+507" },
  { code: "PE", label: "Peru", iso: "+51" },
  { code: "PF", label: "French Polynesia", iso: "+689" },
  { code: "PG", label: "Papua New Guinea", iso: "+675" },
  { code: "PH", label: "Philippines", iso: "+63" },
  { code: "PK", label: "Pakistan", iso: "+92" },
  { code: "PL", label: "Poland", iso: "+48" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    iso: "+508",
  },
  { code: "PN", label: "Pitcairn", iso: "+870" },
  { code: "PR", label: "Puerto Rico", iso: "+1" },
  {
    code: "PS",
    label: "Palestine, State of",
    iso: "+970",
  },
  { code: "PT", label: "Portugal", iso: "+351" },
  { code: "PW", label: "Palau", iso: "+680" },
  { code: "PY", label: "Paraguay", iso: "+595" },
  { code: "QA", label: "Qatar", iso: "+974" },
  { code: "RO", label: "Romania", iso: "+40" },
  { code: "RS", label: "Serbia", iso: "+381" },
  { code: "RU", label: "Russian Federation", iso: "+7" },
  { code: "RW", label: "Rwanda", iso: "+250" },
  { code: "SA", label: "Saudi Arabia", iso: "+966" },
  { code: "SB", label: "Solomon Islands", iso: "+677" },
  { code: "SC", label: "Seychelles", iso: "+248" },
  { code: "SD", label: "Sudan", iso: "+249" },
  { code: "SE", label: "Sweden", iso: "+46" },
  { code: "SG", label: "Singapore", iso: "+65" },
  { code: "SH", label: "Saint Helena", iso: "+290" },
  { code: "SI", label: "Slovenia", iso: "+386" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    iso: "+47",
  },
  { code: "SK", label: "Slovakia", iso: "+421" },
  { code: "SL", label: "Sierra Leone", iso: "+232" },
  { code: "SM", label: "San Marino", iso: "+378" },
  { code: "SN", label: "Senegal", iso: "+221" },
  { code: "SO", label: "Somalia", iso: "+252" },
  { code: "SR", label: "Suriname", iso: "+597" },
  { code: "SS", label: "South Sudan", iso: "+211" },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    iso: "+239",
  },
  { code: "SV", label: "El Salvador", iso: "+503" },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    iso: "+1-721",
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    iso: "+963",
  },
  { code: "SZ", label: "Swaziland", iso: "+268" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    iso: "+1-649",
  },
  { code: "TD", label: "Chad", iso: "+235" },
  {
    code: "TF",
    label: "French Southern Territories",
    iso: "+262",
  },
  { code: "TG", label: "Togo", iso: "+228" },
  { code: "TH", label: "Thailand", iso: "+66" },
  { code: "TJ", label: "Tajikistan", iso: "+992" },
  { code: "TK", label: "Tokelau", iso: "+690" },
  { code: "TL", label: "Timor-Leste", iso: "+670" },
  { code: "TM", label: "Turkmenistan", iso: "+993" },
  { code: "TN", label: "Tunisia", iso: "+216" },
  { code: "TO", label: "Tonga", iso: "+676" },
  { code: "TR", label: "Turkey", iso: "+90" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    iso: "+1-868",
  },
  { code: "TV", label: "Tuvalu", iso: "+688" },
  {
    code: "TW",
    label: "Taiwan, Republic of China",
    iso: "+886",
  },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    iso: "+255",
  },
  { code: "UA", label: "Ukraine", iso: "+380" },
  { code: "UG", label: "Uganda", iso: "+256" },
  {
    code: "US",
    label: "United States",
    iso: "+1",
    suggested: true,
  },
  { code: "UY", label: "Uruguay", iso: "+598" },
  { code: "UZ", label: "Uzbekistan", iso: "+998" },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    iso: "+379",
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    iso: "+1-784",
  },
  { code: "VE", label: "Venezuela", iso: "+58" },
  {
    code: "VG",
    label: "British Virgin Islands",
    iso: "+1-284",
  },
  {
    code: "VI",
    label: "US Virgin Islands",
    iso: "+1-340",
  },
  { code: "VN", label: "Vietnam", iso: "+84" },
  { code: "VU", label: "Vanuatu", iso: "+678" },
  { code: "WF", label: "Wallis and Futuna", iso: "+681" },
  { code: "WS", label: "Samoa", iso: "+685" },
  { code: "XK", label: "Kosovo", iso: "+383" },
  { code: "YE", label: "Yemen", iso: "+967" },
  { code: "ZA", label: "South Africa", iso: "+27" },
  { code: "ZM", label: "Zambia", iso: "+260" },
  { code: "ZW", label: "Zimbabwe", iso: "+263" },
];
